# Generated by Django 3.1.6 on 2022-02-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='technology',
            new_name='url',
        ),
    ]
