# Generated by Django 3.1.6 on 2022-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20220217_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
